[location]
address = "Shanghai, China"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

[shell]
app_icon_color = "error"
font_family = "JetBrainsMono NF"

    [shell.screen_corners]
    enabled = true
    size = 16

[theme]
builtin = "Gruvbox"

    [theme.templates]
    builtin_ids = [ "kitty", "niri" ]
    enable_builtin_templates = false
    enable_community_templates = false