# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ...}: {
  flake.nixosModules.omniLaptopHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/mapper/luks-cb727517-8ea5-46e0-b2dd-293480555332";
        fsType = "ext4";
      };

    boot.initrd.luks.devices."luks-cb727517-8ea5-46e0-b2dd-293480555332".device =
      "/dev/disk/by-uuid/cb727517-8ea5-46e0-b2dd-293480555332";

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/F6CD-5393";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
